id: 77dbccbcd7ec4abc821cd5e948c1c4f9
initial_creation_type: ocr
source_metadata:
  volumes:
    e7b999de7267405b94f94465b167e13a:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: ''
      total_pages: 1902
      volume_number: 64
